# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

pool:
  vmImage: 'Ubuntu 16.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '8.x'
  displayName: 'Install Node.js'

- script: |
    npm install --global gatsby-cli
  displayName: 'install gatsby'

- script: |
    ls /opt/hostedtoolcache/node/8.12.0/x64/bin/
    ls
    gatsby build
  displayName: 'gatsby build'
  workingDirectory: './gatsby-site'
