# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript
resources:
  containers:
  - container: terraform_container
    image: lenisha/vsts-agent-infrastructure:latest

pool:
  vmImage: 'Ubuntu 16.04'

steps:

- task: DownloadBuildArtifacts@0
  inputs:
    buildType: 'specific' # Options: current, specific
    project: 'gatsby-blog' # Required when buildType == Specific
    pipeline: 'great-gasby-blog' # Required when buildType == Specific
    #specificBuildWithTriggering: false # Optional
    #buildVersionToDownload: 'latest' # Required when buildType == Specific# Options: latest, latestFromBranch, specific
    #branchName: 'refs/heads/master' # Required when buildType == Specific && BuildVersionToDownload == LatestFromBranch
    #buildId: # Required when buildType == Specific && BuildVersionToDownload == Specific
    #tags: # Optional
    downloadType: 'single' # Options: single, specific
    artifactName: 'drop' # Required when downloadType == Single
    #itemPattern: '**' # Optional
    downloadPath: 'public' 
    #parallelizationLimit: '8' # Optional


- script: |
    ls -la
  displayName: 'LS'
 
container: terraform_container

steps:

- script: |
    cd deploy/terraform
    terraform init
  displayName: 'Terraform init'